@endpoint = http://localhost:39080/api

### TEST Authorize webhook
GET {{endpoint}}/payment-gateway/authorize


##############################
### DUMMY PAYMENS ACTIONS
##############################

#### To Pay
POST {{endpoint}}/payments/yoWeUqZrJA

#### To Cancel
POST {{endpoint}}/payments/yoWeUqZrJA/cancel

### Triggering External validation orden
PATCH https://vanti-poc.commercelayer.io/api/orders/PzdJhrRpVV
Accept: application/vnd.api+json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJhWEpHakZZQXZuIiwic2x1ZyI6InZhbnRpLXBvYyIsImVudGVycHJpc2UiOmZhbHNlfSwiYXBwbGljYXRpb24iOnsiaWQiOiJuR1ZxYWlWYkJOIiwia2luZCI6InNhbGVzX2NoYW5uZWwiLCJwdWJsaWMiOnRydWV9LCJ0ZXN0Ijp0cnVlLCJleHAiOjE2NzY5NDM5NTYsIm1hcmtldCI6eyJpZCI6WyJWZ0tOTGhEWVZqIl0sInByaWNlX2xpc3RfaWQiOiJlQmJ3eUN5bXdrIiwic3RvY2tfbG9jYXRpb25faWRzIjpbIm9rSmJQdXhseWsiXSwiZ2VvY29kZXJfaWQiOm51bGwsImFsbG93c19leHRlcm5hbF9wcmljZXMiOmZhbHNlfSwicmFuZCI6MC42ODUwMDkzNTEyMDY4Nzc0fQ.-ME7aX5wKUWjzUVkQcZSLfAn1ujIwzrm8YdtTm5lEFtZ4bnILcrRsNJWQN5xOP3t3S_h59rHgWpyDnrutpZwUA
Content-Type: application/vnd.api+json

{
    "data": {
        "type": "orders",
        "id": "PzdJhrRpVV",
        "attributes": {
            "_validate": true
        }
    }
}


### test external order validation
POST {{endpoint}}/external-order-validation
Content-Type: application/json

{
    "data": {
        "id": "wBXVhKzrnq",
        "type": "orders",
        "attributes": { 
            "metadata": {
                "recapchaResponse": "sometoken"
            }
        }
    },
    "included": [
        {
            "id": "DvlGRmhdgX",
            "type": "markets"
        }
    ]
}