image: node:16

stages:
  - Test
  - Deploy

.only changes:
  only:
    changes: &changes
      - pages/**/*
      - src/**/*
      - styles/**/*
      - public/**/*
      - "*.json"
      - "*.js"
      - "*.ts"
      - "*.yaml"
      - .gitlab-ci.yml
      - .gitlab/**/*

Test_Linter:
  stage: Test
  before_script:
    - yarn install
  script:
    - yarn lint
  only:
    refs:
      - main
      - merge_requests
    changes: *changes
  except:
    - tags

pages:
  stage: Deploy
  variables:
    STORYBOOK_PREVIEW_URL: 'https://grupovanti.gitlab.io/Marketplace/web-commerce/main'
  cache:
    key: 'sp-storybook'
    paths:
      - public
  artifacts:
    paths:
      - public
  before_script: 
    - yarn install
    - yarn build-storybook
  script:
    - rm -rf "public/main"
    - mkdir -p "public/main"
    - echo "<!DOCTYPE html><script>window.location.href = '$STORYBOOK_PREVIEW_URL';</script>" > public/index.html
    - mv storybook-static/* "public/main/"
    - rm -rf "public/main/main"

  environment:
    name: Storybook
    url: https://grupovanti.gitlab.io/Marketplace/web-commerce/main/
  only:
    refs:
      - main
    changes: *changes
  except:
    - merge_requests
    - tags
  needs: ["Test_Linter"]
