services:
  app:
    container_name: ${APP_NAME:-VANTI-WEBCOMMERCE}-App
    hostname: app
    image: ${IMAGE_REPO:-aplyca/web/vanti-app}${IMAGE_TAG:-}
    working_dir: /app
    build:
      context: .
      dockerfile: etc/docker/Dockerfile.app
      target: ${TARGET_IMAGE:-dev}
      cache_from:
        - ${IMAGE_REPO:-aplyca/web/vanti-app}${IMAGE_TAG:-}
        - ${IMAGE_REPO:-aplyca/web/vanti-app}${IMAGE_CACHE_TAG:-:latest}
      args:
        CONTENTFUL_ENVIRONMENT: ${CONTENTFUL_ENVIRONMENT:-master}
        CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID:-3brzg7q3bvg1}
        CONTENTFUL_DELIVERY_API_TOKEN: ${CONTENTFUL_DELIVERY_API_TOKEN:?err}
        CONTENTFUL_PREVIEW_API_TOKEN: ${CONTENTFUL_PREVIEW_API_TOKEN:?err}
        SENTRY_LOG_LEVEL: debug
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-}
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./src:/app/src:rw
      - ./pages:/app/pages:rw
      - ./public:/app/public:rw
      - ./styles:/app/styles:rw
      - ./tailwind.config.js:/app/tailwind.config.js:rw
      - ./next.config.js:/app/next.config.js:rw
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONTENTFUL_ENVIRONMENT: ${CONTENTFUL_ENVIRONMENT:-master}
      CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID:-3brzg7q3bvg1}
      CONTENTFUL_DELIVERY_API_TOKEN: ${CONTENTFUL_DELIVERY_API_TOKEN:?err}
      CONTENTFUL_PREVIEW_API_TOKEN: ${CONTENTFUL_PREVIEW_API_TOKEN:?err}
      INVALIDATE_SECRET_TOKEN: ${INVALIDATE_SECRET_TOKEN:-test}
      COMMERCELAYER_ENDPOINT: ${COMMERCELAYER_ENDPOINT:-https://vanti-poc.commercelayer.io}
      COMMERCELAYER_CLIENT_ID: ${COMMERCELAYER_CLIENT_ID:-}
      COMMERCELAYER_CLIENT_SECRET: ${COMMERCELAYER_CLIENT_SECRET:-}
      COMMERCELAYER_MARKET_SCOPE: ${COMMERCELAYER_MARKET_SCOPE:-}
    networks:
      public: ~
    restart: unless-stopped
  storybook:
    container_name: ${APP_NAME:-VANTI-WEBCOMMERCE}-Storybook
    hostname: storybook
    image: ${IMAGE_REPO:-aplyca/web/vanti-sb}${IMAGE_TAG:-}
    working_dir: /app
    build:
      context: .
      dockerfile: etc/docker/Dockerfile.sb
      cache_from:
        - ${IMAGE_REPO:-aplyca/web/vanti-sb}${IMAGE_TAG:-}
        - ${IMAGE_REPO:-aplyca/web/vanti-sb}${IMAGE_CACHE_TAG:-:latest}
    ports:
      - "${STORYBOOK_PORT:-6006}:6006"
    volumes:
      - ./src:/app/src:rw
      - ./pages:/app/pages:rw
      - ./public:/app/public:rw
      - ./styles:/app/styles:rw
      - ./tailwind.config.js:/app/tailwind.config.js:rw
      - ./.storybook:/app/.storybook:rw
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    networks:
      public: ~
    restart: unless-stopped

# volumes:
#   node_modules:
#   packages_file:
#   packages_lock:

networks:
  public:
    name: ${APP_NAME:-VANTI-WEBCOMMERCE}-Public

version: "3.7"
