services:
  app:
    container_name: ${APP_NAME:-VANTI-WEBCOMMERCE}-App
    hostname: app
    image: ${IMAGE_REPO:-aplyca/web/vanti-app}${IMAGE_TAG:-}
    working_dir: /app
    build:
      context: .
      dockerfile: etc/docker/Dockerfile.app
      target: ${TARGET_IMAGE:-dev}
      cache_from:
        - ${IMAGE_REPO:-aplyca/web/vanti-app}${IMAGE_TAG:-}
        - ${IMAGE_REPO:-aplyca/web/vanti-app}${IMAGE_CACHE_TAG:-:latest}
      args:
        NODE_ENV: ${NODE_ENV:-development}
        CONTENTFUL_ENVIRONMENT: ${CONTENTFUL_ENVIRONMENT:-master}
        CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID:-3brzg7q3bvg1}
        CONTENTFUL_DELIVERY_API_TOKEN: ${CONTENTFUL_DELIVERY_API_TOKEN:?err}
        CONTENTFUL_PREVIEW_API_TOKEN: ${CONTENTFUL_PREVIEW_API_TOKEN:?err}
        REVALIDATE_SECRET_TOKEN: ${REVALIDATE_SECRET_TOKEN:-test}
        NEXT_PUBLIC_COMMERCELAYER_ENDPOINT: ${NEXT_PUBLIC_COMMERCELAYER_ENDPOINT:-https://vanti-poc.commercelayer.io}
        NEXT_PUBLIC_COMMERCELAYER_CLIENT_ID: ${NEXT_PUBLIC_COMMERCELAYER_CLIENT_ID:-}
        NEXT_PUBLIC_COMMERCELAYER_GASODOMESTICOS_MARKET_ID: ${NEXT_PUBLIC_COMMERCELAYER_GASODOMESTICOS_MARKET_ID:-}
        COMMERCELAYER_INTEGRATION_CLIENT_ID: ${COMMERCELAYER_INTEGRATION_CLIENT_ID:-}
        COMMERCELAYER_INTEGRATION_CLIENT_SECRET: ${COMMERCELAYER_INTEGRATION_CLIENT_SECRET:-}
        COMMERCELAYER_DEFAULT_SHIPPING_METHOD_ID: ${COMMERCELAYER_DEFAULT_SHIPPING_METHOD_ID:-}
        NEXT_PUBLIC_COMMERCELAYER_VANTILISTO_MARKET_ID: ${NEXT_PUBLIC_COMMERCELAYER_VANTILISTO_MARKET_ID:-}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2:-}
        RECAPTCHA_SECRET_KEY_V2: ${RECAPTCHA_SECRET_KEY_V2:-}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V3: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V3:-}
        RECAPTCHA_SECRET_KEY_V3: ${RECAPTCHA_SECRET_KEY_V3:-}
        SMTP_HOST: ${SMTP_HOST:-mailer}
        SMTP_PORT: ${SMTP_HOST:-1025}
        SMTP_USER: ${SMTP_HOST:-null}
        SMTP_PASSWORD: ${SMTP_HOST:-null}
        ALGOLIASEARCH_APP_ID: ${ALGOLIASEARCH_APP_ID:-DU18JA7AT2}
        ALGOLIASEARCH_READ_API_KEY: ${ALGOLIASEARCH_READ_API_KEY:-}
        ALGOLIASEARCH_WRITE_API_KEY: ${ALGOLIASEARCH_WRITE_API_KEY:-}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-secret}
        NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID:-}
        GENESYS_CLIENT_ID: ${GENESYS_CLIENT_ID:-}
        GENESYS_CLIENT_SECRET: ${GENESYS_CLIENT_SECRET:-}
        VANTILISTO_USER_NAME: ${VANTILISTO_USER_NAME:-}
        VANTILISTO_USER_PASSWORD: ${VANTILISTO_USER_PASSWORD:-}
        DEFAULT_DOMAIN: ${DEFAULT_DOMAIN:-}
    ports:
      - "${APP_PORT_PREFIX:-39}080:3000"
      - "${APP_PORT_PREFIX:-39}229:9229"
    volumes:
      - ./src:/app/src:rw
      - ./pages:/app/pages:rw
      - ./public:/app/public:rw
      - ./styles:/app/styles:rw
      - ./tailwind.config.js:/app/tailwind.config.js:rw
      - ./next.config.js:/app/next.config.js:rw
      - ./middleware.ts:/app/middleware.ts:rw
      - ./.eslintrc.json:/app/.eslintrc.json:rw
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONTENTFUL_ENVIRONMENT: ${CONTENTFUL_ENVIRONMENT:-master}
      CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID:-3brzg7q3bvg1}
      CONTENTFUL_DELIVERY_API_TOKEN: ${CONTENTFUL_DELIVERY_API_TOKEN:?err}
      CONTENTFUL_PREVIEW_API_TOKEN: ${CONTENTFUL_PREVIEW_API_TOKEN:?err}
      REVALIDATE_SECRET_TOKEN: ${REVALIDATE_SECRET_TOKEN:-test}
      NEXT_PUBLIC_COMMERCELAYER_ENDPOINT: ${NEXT_PUBLIC_COMMERCELAYER_ENDPOINT:-https://vanti-poc.commercelayer.io}
      NEXT_PUBLIC_COMMERCELAYER_CLIENT_ID: ${NEXT_PUBLIC_COMMERCELAYER_CLIENT_ID:-}
      NEXT_PUBLIC_COMMERCELAYER_GASODOMESTICOS_MARKET_ID: ${NEXT_PUBLIC_COMMERCELAYER_GASODOMESTICOS_MARKET_ID:-}
      COMMERCELAYER_INTEGRATION_CLIENT_ID: ${COMMERCELAYER_INTEGRATION_CLIENT_ID:-}
      COMMERCELAYER_INTEGRATION_CLIENT_SECRET: ${COMMERCELAYER_INTEGRATION_CLIENT_SECRET:-}
      COMMERCELAYER_DEFAULT_SHIPPING_METHOD_ID: ${COMMERCELAYER_DEFAULT_SHIPPING_METHOD_ID:-}
      NEXT_PUBLIC_COMMERCELAYER_VANTILISTO_MARKET_ID: ${NEXT_PUBLIC_COMMERCELAYER_VANTILISTO_MARKET_ID:-}
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2:-}
      RECAPTCHA_SECRET_KEY_V2: ${RECAPTCHA_SECRET_KEY_V2:-}
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V3: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V3:-}
      RECAPTCHA_SECRET_KEY_V3: ${RECAPTCHA_SECRET_KEY_V3:-}
      SMTP_HOST: ${SMTP_HOST:-mailer}
      SMTP_PORT: ${SMTP_HOST:-1025}
      SMTP_USER: ${SMTP_HOST:-null}
      SMTP_PASSWORD: ${SMTP_HOST:-null}
      ALGOLIASEARCH_APP_ID: ${ALGOLIASEARCH_APP_ID:-DU18JA7AT2}
      ALGOLIASEARCH_READ_API_KEY: ${ALGOLIASEARCH_READ_API_KEY:-}
      ALGOLIASEARCH_WRITE_API_KEY: ${ALGOLIASEARCH_WRITE_API_KEY:-}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-secret}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID:-}
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN:-}
      HTTP_BASIC_AUTH: ${HTTP_BASIC_AUTH:-}
      GENESYS_CLIENT_ID: ${GENESYS_CLIENT_ID:-}
      GENESYS_CLIENT_SECRET: ${GENESYS_CLIENT_SECRET:-}
      VANTILISTO_USER_NAME: ${VANTILISTO_USER_NAME:-}
      VANTILISTO_USER_PASSWORD: ${VANTILISTO_USER_PASSWORD:-}
      PLACE_TO_PAY_ENDPOINT: ${PLACE_TO_PAY_ENDPOINT:-}
      PLACE_TO_PAY_LOGIN: ${PLACE_TO_PAY_LOGIN:-}
      PLACE_TO_PAY_SECRET_KEY: ${PLACE_TO_PAY_SECRET_KEY:-}
      PLACE_TO_PAY_RETURN_URL: ${PLACE_TO_PAY_RETURN_URL:-}
      COMMERCELAYER_P2P_SHARED_SECRET: ${COMMERCELAYER_P2P_SHARED_SECRET:-}
    networks:
      - public
    restart: unless-stopped
  storybook:
    container_name: ${APP_NAME:-VANTI-WEBCOMMERCE}-Storybook
    hostname: storybook
    image: ${IMAGE_REPO:-aplyca/web/vanti-sb}${IMAGE_TAG:-}
    working_dir: /app
    build:
      context: .
      dockerfile: etc/docker/Dockerfile.sb
      cache_from:
        - ${IMAGE_REPO:-aplyca/web/vanti-sb}${IMAGE_TAG:-}
        - ${IMAGE_REPO:-aplyca/web/vanti-sb}${IMAGE_CACHE_TAG:-:latest}
    ports:
      - "${APP_PORT_PREFIX:-39}006:6006"
    volumes:
      - ./src:/app/src:rw
      - ./pages:/app/pages:rw
      - ./public:/app/public:rw
      - ./styles:/app/styles:rw
      - ./tailwind.config.js:/app/tailwind.config.js:rw
      - ./.storybook:/app/.storybook:rw
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    networks:
      - public
    restart: unless-stopped
  mailer:
    container_name: ${APP_NAME:-VANTI-WEBCOMMERCE}-Mailer
    hostname: mailer
    image: mailhog/mailhog
    tty: true
    expose:
      - 1025
    ports:
      - "${APP_PORT_PREFIX:-39}025:8025"
    networks:
      - public
    restart: unless-stopped
networks:
  public:
    name: ${APP_NAME:-VANTI-WEBCOMMERCE}-Public

version: "3.7"
