##### Building Base image #####
FROM node:16-alpine

RUN mkdir -p /app
WORKDIR /app

## Cooy config files
COPY package.json yarn.loc[k] /app/

## Install packages
RUN yarn install

## Cooy config files
COPY tailwind.config.js postcss.config.js next* *.json /app/

## Copy project files
COPY .storybook /app/.storybook
COPY src /app/src
COPY pages /app/pages
COPY public /app/public
COPY styles /app/styles

EXPOSE 6006
CMD [ "yarn", "storybook" ]
